package(default_visibility = ["//visibility:public"])

java_library(
    name = "axis",
    exported_deps = [
      ":activation",
      ":discovery",
      ":jaxrpc",
      ":logging",
      ":mail",
      ":saaj",
    ],
    exports = ["@axis//jar"],
)

java_library(
    name = "discovery",
    exports = ["@discovery//jar"],
)

java_library(
    name = "logging",
    exports = ["@logging//jar"],
)

java_library(
    name = "jaxrpc",
    exports = ["@jaxrpc//jar"],
)

java_library(
    name = "mail",
    exports = ["@mail//jar"],
)

java_library(
    name = "activation",
    exports = ["@activation//jar"],
)

java_library(
    name = "wsdl4j",
    exports = ["@wsdl4j//jar"],
)

java_library(
    name = "saaj",
    exports = ["@saaj//jar"],
)
